package gift.dhamma.pali;

import android.app.SearchManager;
import android.content.ContentProvider;
import android.content.ContentValues;
import android.content.Context;
import android.content.SharedPreferences;
import android.database.Cursor;
import android.database.MatrixCursor;
import android.net.Uri;
import android.provider.BaseColumns;

import java.io.BufferedReader;
import java.io.Closeable;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.List;

/**
 * Suggestions for Android's system search: the word list the dictionary can actually resolve.
 *
 * WHY A PROVIDER AND NOT THE SITE: dict.dhamma.gift is a Trusted Web Activity — Chrome renders the
 * page in its own process, so when the search framework asks for suggestions there is no bridge to
 * the page's JavaScript. The words therefore travel with the app (assets/dpd_headwords.txt and
 * assets/dpd_forms.txt, generated by scripts/build-dict-headwords.py from the very bundles the site
 * searches with) and a tap hands the word to the site as https://dict.dhamma.gift/?q=<word> — the
 * same ?q= contract the share target and the text-selection entry already use.
 *
 * TWO LISTS, ONE RANKING: headwords are scanned before inflected forms, so a headword always
 * outranks a mere inflection for the same prefix. Both scans are folding, allocation-free prefixes
 * over one String per asset: 130k words cost ~4MB of heap and a couple of milliseconds per
 * keystroke, where an array of 130k String objects would cost several times that for no benefit.
 *
 * FOLDING: Pali diacritics are not optional to type and are not what a hurried reader types either,
 * so comparisons ignore case and diacritics ("atthananda" finds "atthānanda"). The DISPLAYED word is
 * always the asset's own spelling, never the folded one.
 *
 * RECENTS: the search framework never tells a provider which query the user submitted, so
 * LauncherActivity records it (rememberQuery) when ACTION_SEARCH arrives and this provider shows
 * those first — the app's own history of searches typed into system search. It is not the site's
 * history: that lives in the page's localStorage, which a TWA cannot read.
 */
public class DgDictSuggestProvider extends ContentProvider {

    public static final String AUTHORITY = "gift.dhamma.pali.suggest";

    private static final String[] COLUMNS = {
            BaseColumns._ID,
            SearchManager.SUGGEST_COLUMN_TEXT_1,
            SearchManager.SUGGEST_COLUMN_INTENT_DATA,
    };

    private static final int MAX_SUGGESTIONS = 12;
    private static final int MAX_RECENT = 10;
    private static final int MAX_RECENT_SHOWN = 3;

    private static final String HEADWORDS_ASSET = "dpd_headwords.txt";
    private static final String FORMS_ASSET = "dpd_forms.txt";

    private static final String PREFS = "dg_dict_suggest";
    private static final String PREFS_RECENT = "recent";

    private static final String SEARCH_URL = "https://dict.dhamma.gift/?q=";

    // Loaded once in onCreate: 1.8MB of text, ~4MB of heap, and the only state this provider has.
    private String headwords = "";
    private String forms = "";

    @Override
    public boolean onCreate() {
        headwords = readAsset(HEADWORDS_ASSET);
        forms = readAsset(FORMS_ASSET);
        return true;
    }

    /**
     * Remembers a submitted query so it can be offered first next time. Called by LauncherActivity
     * on ACTION_SEARCH — the one place that sees a query the reader actually meant, as opposed to
     * the half-typed prefixes a provider is asked about on every keystroke.
     */
    public static void rememberQuery(Context context, String query) {
        if (context == null || query == null) return;
        String word = query.trim();
        if (word.isEmpty()) return;

        List<String> recent = readRecent(context);
        // Case-insensitive dedupe, then most-recent-first: a reader who searches the same word
        // twice should not get it twice in the list.
        for (int i = recent.size() - 1; i >= 0; i--) {
            if (recent.get(i).equalsIgnoreCase(word)) recent.remove(i);
        }
        recent.add(0, word);
        while (recent.size() > MAX_RECENT) recent.remove(recent.size() - 1);

        StringBuilder joined = new StringBuilder();
        for (String item : recent) {
            if (joined.length() > 0) joined.append('\n');
            joined.append(item);
        }
        preferences(context).edit().putString(PREFS_RECENT, joined.toString()).apply();
    }

    @Override
    public Cursor query(Uri uri, String[] projection, String selection, String[] selectionArgs,
                        String sortOrder) {
        String query = queryOf(selection, selectionArgs);
        String folded = fold(query);

        List<String> words = new ArrayList<String>();

        // 1. The reader's own recent searches, when they match what is being typed.
        for (String word : readRecent(getContext())) {
            if (words.size() >= MAX_RECENT_SHOWN) break;
            if (folded.isEmpty() || fold(word).startsWith(folded)) {
                if (!words.contains(word)) words.add(word);
            }
        }

        // 2. Words, then inflected forms: a headword answers "what is this word", an inflection only
        //    answers "where does this form lead", so the word goes first.
        collect(headwords, folded, words);
        collect(forms, folded, words);

        // An exact match is what the reader most likely wants, and inside a sorted prefix range it
        // can sit anywhere ("gacchati" comes after "gaccha", "gacchanta"…), so it is hoisted to the
        // top before the rows are built.
        if (!folded.isEmpty()) {
            for (int i = 1; i < words.size(); i++) {
                if (fold(words.get(i)).equals(folded)) {
                    words.add(0, words.remove(i));
                    break;
                }
            }
        }

        MatrixCursor cursor = new MatrixCursor(COLUMNS);
        for (int i = 0; i < words.size(); i++) {
            String word = words.get(i);
            cursor.addRow(new Object[] {(long) i, word, SEARCH_URL + Uri.encode(word)});
        }
        return cursor;
    }

    @Override
    public String getType(Uri uri) {
        return SearchManager.SUGGEST_MIME_TYPE;
    }

    @Override
    public Uri insert(Uri uri, ContentValues values) {
        // Read-only: the word list is an asset and the recents are written by rememberQuery.
        return null;
    }

    @Override
    public int delete(Uri uri, String selection, String[] selectionArgs) {
        return 0;
    }

    @Override
    public int update(Uri uri, ContentValues values, String selection, String[] selectionArgs) {
        return 0;
    }

    // ---------------------------------------------------------------------------------------------
    // Internals

    /** Appends every entry of the (newline-separated) list that starts with the folded query. */
    private static void collect(String list, String foldedQuery, List<String> into) {
        if (list == null || list.isEmpty()) return;

        int position = 0;
        int length = list.length();
        while (position < length && into.size() < MAX_SUGGESTIONS) {
            int end = list.indexOf('\n', position);
            if (end < 0) end = length;
            if (isPrefix(list, position, end, foldedQuery)) {
                String word = list.substring(position, end);
                if (!into.contains(word)) into.add(word);
            }
            position = end + 1;
        }
    }

    /** True when the line at [start,end) begins with the already-folded query. */
    private static boolean isPrefix(String text, int start, int end, String foldedQuery) {
        if (foldedQuery.isEmpty()) return true;
        if (end - start < foldedQuery.length()) return false;
        for (int i = 0; i < foldedQuery.length(); i++) {
            if (fold(text.charAt(start + i)) != foldedQuery.charAt(i)) return false;
        }
        return true;
    }

    private static String queryOf(String selection, String[] selectionArgs) {
        // searchable.xml sets searchSuggestSelection=" ?", which is how the framework marks the
        // query as selectionArgs[0]; some callers pass it in the selection itself instead.
        if (selectionArgs != null && selectionArgs.length > 0 && selectionArgs[0] != null) {
            return selectionArgs[0].trim();
        }
        if (selection == null) return "";
        String trimmed = selection.trim();
        return trimmed.startsWith("?") ? trimmed.substring(1).trim() : trimmed;
    }

    private static String fold(String text) {
        StringBuilder out = new StringBuilder(text.length());
        for (int i = 0; i < text.length(); i++) out.append(fold(text.charAt(i)));
        return out.toString();
    }

    /**
     * Case- and diacritic-insensitive form of one character. Pali uses a small fixed set of
     * diacritics, so this is a switch rather than java.text.Normalizer: the normalizer would also
     * erase the distinction between ṭ/ḍ and t/d, which is exactly the distinction a reader is
     * halfway through typing.
     *
     * The letters are written as escapes on purpose — the generated project is built with javac's
     * default encoding, and a source file whose diacritics depend on that default is a build that
     * breaks on whichever machine reads it first.
     */
    private static char fold(char c) {
        if (c >= 'A' && c <= 'Z') return (char) (c + 32);
        switch (c) {
            case '\u0101': return 'a'; // ā
            case '\u012b': return 'i'; // ī
            case '\u016b': return 'u'; // ū
            case '\u1e6d': return 't'; // ṭ
            case '\u1e0d': return 'd'; // ḍ
            case '\u1e47': return 'n'; // ṇ
            case '\u1e45': return 'n'; // ṅ
            case '\u00f1': return 'n'; // ñ
            case '\u1e43': return 'm'; // ṃ
            case '\u1e41': return 'm'; // ṁ
            case '\u1e37': return 'l'; // ḷ
            case '\u1e39': return 'l'; // ḹ
            case '\u015b': return 's'; // ś
            case '\u1e63': return 's'; // ṣ
            default: return c;
        }
    }

    private String readAsset(String name) {
        Context context = getContext();
        if (context == null) return "";

        InputStream stream = null;
        BufferedReader reader = null;
        try {
            stream = context.getAssets().open(name);
            reader = new BufferedReader(new InputStreamReader(stream, "UTF-8"));
            StringBuilder text = new StringBuilder(1 << 20);
            String line;
            while ((line = reader.readLine()) != null) {
                text.append(line).append('\n');
            }
            return text.toString();
        } catch (IOException e) {
            // A provider that throws would break the system search UI itself; an empty list only
            // means no suggestions.
            return "";
        } finally {
            close(reader);
            close(stream);
        }
    }

    private static void close(Closeable closeable) {
        if (closeable == null) return;
        try {
            closeable.close();
        } catch (IOException ignored) {
            // Nothing useful to do while shutting a stream down.
        }
    }

    private static List<String> readRecent(Context context) {
        List<String> recent = new ArrayList<String>();
        if (context == null) return recent;
        String stored = preferences(context).getString(PREFS_RECENT, "");
        if (stored == null || stored.isEmpty()) return recent;
        for (String line : stored.split("\n")) {
            String word = line.trim();
            if (!word.isEmpty()) recent.add(word);
        }
        return recent;
    }

    private static SharedPreferences preferences(Context context) {
        return context.getSharedPreferences(PREFS, Context.MODE_PRIVATE);
    }
}
